branches:
  only:
    - master
sudo: false
dist: trusty
language: ruby
rvm: 2.6.1
addons:
  postgresql: 9.6
cache: bundler
bundler_args: --retry=6
before_script:
  - bundle exec rake --trace db:setup
script:
  - bundle exec rspec --format progress --tag ~type:acceptance
notifications:
  email: false
