sudo: false
language: ruby
rvm:
  - "2.2.3"
cache: bundler
bundler_args: --retry=6
script:
  - bundle exec rake
notifications:
  email: false
addons:
   postgresql: "9.3"
before_script:
  - export OXT_DB_USER=postgres
  - export OXT_DB_PASS=
  - export OXT_TEST_DB=travis_ci_test
  - cd spec/dummy; bundle exec bin/rake db:create:all db:migrate
