default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['RESCUE_FROM_DB_USER'] %>
  password: <%= ENV['RESCUE_FROM_DB_PASS'] %>
  database: <%= ENV['RESCUE_FROM_TEST_DB'] || 'rescue_from_test' %>

development:
  <<: *default

test:
  <<: *default
