name: Tests
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  tests:
    timeout-minutes: 30
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Setup
        run: bundle install
      - name: Test
        run: bundle exec rake spec
