name: Tests
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  tests:
    timeout-minutes: 30
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true
      - name: Test
        run: bundle exec rake spec
